### ISSUE TITLE
Split window keybinds incorrect

### ISSUE THREAD

**Issue by geertjanknapen1** [l9c/tmux_cheat_sheet_data#14]
The listed keybinds to split the windows seem incorrect (at least, they do not work for me)
<img width="286" alt="image" src="https://github.com/l9c/tmux_cheat_sheet_data/assets/33750300/4e2c7b94-15bd-4a7c-b30f-878474856c44">

Correct ones;
- Horizontal: `Ctrl` + `B`  `|`
- Vertical: `Ctrl` + `B`  `-`

Tmux version: `tmux 3.2a`
OS Version: `Ubuntu 22.04.3 LTS`

**Comment by l9c** [comment]
The cheat sheet reflects [the default key bindings](https://github.com/tmux/tmux/blob/master/key-bindings.c#L354). Please check your tmux config for this issue.
