### ISSUE TITLE
Incorrect Resize Pane Keybind

### ISSUE THREAD

**Issue by Itzdlg** [l9c/tmux_cheat_sheet_data#7]
On the cheat sheet, it states that resizing is Ctrl+B then Ctrl+(arrow), however the default is Ctrl+B then Alt+(arrow). With Ubuntu 20.04, the keybind listed simply changes the active pane.

Also, just want to say thank you for the cheat sheet, I wouldn't remember any of the tmux shortcuts otherwise!

**Comment by l9c** [comment]
Hi, @Itzdlg. I can't reproduce your problem on a fresh Ubuntu 20.04. You may need to double check the config.

**Comment by Itzdlg** [comment]
So, I've gone back and tried again with my old terminal Putty and the issue still stands, but then with Termius it works as intended. It would seem that Putty is switching input of ctrl and alt, or somehow changing the binds.. I've no clue, but if it is fine on a local machine (or the binds match the ones in the default config) then it makes sense to keep that bind. Apologies!
