### ISSUE TITLE
A pdf version

### ISSUE THREAD

**Issue by AtaraxiaZ** [l9c/tmux_cheat_sheet_data#9]
Hello, the cheatsheet really help me a lot. Great job! 
But I wonder If we can get a PDF version, I want to save it to my local computer.

**Comment by pzhlkj6612** [comment]
Hi! I think you can save the cheat sheet by executing the "print" command (Ctrl+P or Command+P) in your web browser and choose the "save to PDF" function.

**Comment by AtaraxiaZ** [comment]
ok，I will give it a try. Thanks!
